project_name: gocachex

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gocachex-cli
    main: ./examples/cli
    binary: gocachex-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: gocachex
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - examples/configs/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: chmenegatti
    name: gocachex
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## GoCacheX {{ .Tag }} ({{ .Date }})
    
    Welcome to this new release of GoCacheX!

  footer: |
    ## Installation
    
    ```bash
    go get github.com/chmenegatti/gocachex@{{ .Tag }}
    ```
    
    **Full Changelog**: https://github.com/chmenegatti/gocachex/compare/{{ .PreviousTag }}...{{ .Tag }}

  extra_files:
    - glob: ./examples/configs/*.json
    - glob: ./docs/*.md

announce:
  skip: true
